import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import { Button, ButtonGroup } from '@chakra-ui/react'
import { Text } from '@chakra-ui/react'

export default function Home() {
  const router = useRouter()

  return (
    <div className={styles.container}>
      <Head>
        <title>Personality Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Text fontSize='3xl' color={'#050937'} fontWeight={800} textAlign={'center'} maxWidth={600} maxHeight={300} marginBottom={30}>
          Test: Are you an introvert or an extrovert?
        </Text>
        <Text fontSize='xl' color={'#050937'} textAlign={'center'} maxWidth={600} maxHeight={300} marginBottom={30}>
          So do you consider yourself more of an introvert or an extrovert? Take this test, put together with input from psychoanalyst Sandrine Dury, and find out
        </Text>

        <Button colorScheme='twitter' onClick={() => router.push('/personality-test')} aria-label={'start'}>Start personality test</Button>
      </main>

    </div>
  )
}
